kind: Service
apiVersion: v1
metadata:
    name: freechat-service
spec:
    selector:
        app: freechat
    ports:
      - protocol: "TCP"
        # port accessible inside cluster
        port: 3000
        # port to foward to inside the pod
        targetPort: 3000
        nodePort: 30000
    type: NodePort
     

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: freechat-deployment
    labels:
        app: freechat
spec:
    replicas: 5
    selector:
        matchLabels:
            app: freechat
    template:
        metadata:
            labels:
                app: freechat
        spec:
            containers:
              - name: freechat
                image: jiewuu/freechat:1.1
                ports:
                - containerPort: 3000